In [1]:
import pandas as pd
import yfinance as yf

print(pd.__version__)
print(yf.__version__)

3.0.3
1.5.1

In [2]:
apple_data = yf.download(
    "AAPL",
    start="2025-01-01",
    end="2026-01-01"
)

apple_data.head()

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker            AAPL        AAPL        AAPL        AAPL      AAPL
Date
2025-01-02  242.301910  247.518580  240.284799  247.349646  55740700
2025-01-03  241.815018  242.629804  240.354349  241.815018  40244100
2025-01-06  243.444626  245.759836  241.656050  242.759004  45045600
2025-01-07  240.672318  243.991110  239.817777  241.437418  40856000
2025-01-08  241.159225  242.162823  238.526055  240.384178  37628900

In [3]:
apple_data.shape

(250, 5)

In [4]:
apple_data.describe()

Price        Close        High         Low        Open        Volume
Ticker        AAPL        AAPL        AAPL        AAPL          AAPL
count   250.000000  250.000000  250.000000  250.000000  2.500000e+02
mean    231.349892  233.833559  228.745397  231.156008  5.417578e+07
std      26.574991   26.312842   26.784552   26.634415  2.337841e+07
min     171.513748  189.339558  168.320629  171.046232  1.791060e+07
25%     209.182632  211.166303  206.993097  209.142784  4.086605e+07
50%     229.226494  231.707152  226.505888  228.967223  4.778135e+07
75%     253.615002  255.542047  250.832889  253.727193  5.723262e+07
max     285.659271  288.084759  282.774617  285.669263  1.843959e+08

In [5]:
apple_data.columns = apple_data.columns.get_level_values(0)

apple_data = apple_data.reset_index()

apple_data.head()

Price       Date       Close        High         Low        Open    Volume
0     2025-01-02  242.301910  247.518580  240.284799  247.349646  55740700
1     2025-01-03  241.815018  242.629804  240.354349  241.815018  40244100
2     2025-01-06  243.444626  245.759836  241.656050  242.759004  45045600
3     2025-01-07  240.672318  243.991110  239.817777  241.437418  40856000
4     2025-01-08  241.159225  242.162823  238.526055  240.384178  37628900

In [7]:
# Check Data Quality
# Check missing values in each column
print("Missing values:")
print(apple_data.isnull().sum())

# Check the number of duplicate rows
print("\nDuplicate rows:")
print(apple_data.duplicated().sum())

Missing values:
Price
Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

Duplicate rows:
0

In [8]:
# ==========================================================
#  Add Business Metadata
#
# Business Purpose:
# To prepare the dataset for future integration with multiple
# financial instruments and vendors. We add the instrument
# ticker and the original data source so every record can be
# identified and traced.
# ==========================================================

# Add the stock ticker
apple_data["Ticker"] = "AAPL"

# Add the data source
apple_data["DataSource"] = "Yahoo Finance"

# Display the first 5 rows
apple_data.head()

Price,Date,Close,High,Low,Open,Volume,Ticker,DataSource
0,2025-01-02,242.301910,247.518580,240.284799,247.349646,55740700,AAPL,Yahoo Finance
1,2025-01-03,241.815018,242.629804,240.354349,241.815018,40244100,AAPL,Yahoo Finance
2,2025-01-06,243.444626,245.759836,241.656050,242.759004,45045600,AAPL,Yahoo Finance
3,2025-01-07,240.672318,243.991110,239.817777,241.437418,40856000,AAPL,Yahoo Finance
4,2025-01-08,241.159225,242.162823,238.526055,240.384178,37628900,AAPL,Yahoo Finance

In [9]:
# Remove the Column Index Name

# Remove the column index name
apple_data.columns.name = None

# Display the first 5 rows
apple_data.head()

,Date,Close,High,Low,Open,Volume,Ticker,DataSource
0,2025-01-02,242.301910,247.518580,240.284799,247.349646,55740700,AAPL,Yahoo Finance
1,2025-01-03,241.815018,242.629804,240.354349,241.815018,40244100,AAPL,Yahoo Finance
2,2025-01-06,243.444626,245.759836,241.656050,242.759004,45045600,AAPL,Yahoo Finance
3,2025-01-07,240.672318,243.991110,239.817777,241.437418,40856000,AAPL,Yahoo Finance
4,2025-01-08,241.159225,242.162823,238.526055,240.384178,37628900,AAPL,Yahoo Finance

In [10]:
# Download Microsoft Market Data

# Download Microsoft historical data
microsoft_data = yf.download(
    "MSFT",
    start="2025-01-01",
    end="2026-01-01"
)

# Display the first 5 rows
microsoft_data.head()

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker            MSFT        MSFT        MSFT        MSFT      MSFT
Date
2025-01-02  413.672638  421.074847  409.986387  420.541170  16896500
2025-01-03  418.386749  419.058770  414.621419  416.143343  16662900
2025-01-06  422.833954  429.228102  420.491744  422.982189  20573600
2025-01-07  417.418213  425.601139  415.866612  423.970489  18139100
2025-01-08  419.582489  421.964238  416.597906  418.495379  15054600

In [11]:

# Prepare Microsoft Data

# Remove the second column level (Ticker)
microsoft_data.columns = microsoft_data.columns.get_level_values(0)

# Convert the Date index into a normal column
microsoft_data = microsoft_data.reset_index()

# Remove the remaining column index name
microsoft_data.columns.name = None

# Add business metadata
microsoft_data["Ticker"] = "MSFT"
microsoft_data["DataSource"] = "Yahoo Finance"

# Display the first 5 rows
microsoft_data.head()

,Date,Close,High,Low,Open,Volume,Ticker,DataSource
0,2025-01-02,413.672638,421.074847,409.986387,420.541170,16896500,MSFT,Yahoo Finance
1,2025-01-03,418.386749,419.058770,414.621419,416.143343,16662900,MSFT,Yahoo Finance
2,2025-01-06,422.833954,429.228102,420.491744,422.982189,20573600,MSFT,Yahoo Finance
3,2025-01-07,417.418213,425.601139,415.866612,423.970489,18139100,MSFT,Yahoo Finance
4,2025-01-08,419.582489,421.964238,416.597906,418.495379,15054600,MSFT,Yahoo Finance

In [12]:
# Download NVIDIA Market Data

# Download NVIDIA historical market data
nvidia_data = yf.download(
    "NVDA",
    start="2025-01-01",
    end="2026-01-01"
)

# Display the first 5 rows
nvidia_data.head()

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open     Volume
Ticker            NVDA        NVDA        NVDA        NVDA       NVDA
Date
2025-01-02  138.264694  138.834515  134.585907  135.955453  198247200
2025-01-03  144.422684  144.852536  139.684231  139.964138  229322500
2025-01-06  149.381042  152.110159  147.771585  148.541321  265377400
2025-01-07  140.094086  153.079835  139.964123  152.979862  351782200
2025-01-08  140.064102  143.902841  137.514934  142.533294  227349900

In [13]:
# ==========================================================
# Prepare NVIDIA Data



# Remove the second column level (Ticker)
nvidia_data.columns = nvidia_data.columns.get_level_values(0)

# Convert the Date index into a normal column
nvidia_data = nvidia_data.reset_index()

# Remove the remaining column index name
nvidia_data.columns.name = None

# Add business metadata
nvidia_data["Ticker"] = "NVDA"
nvidia_data["DataSource"] = "Yahoo Finance"

# Display the first 5 rows
nvidia_data.head()

,Date,Close,High,Low,Open,Volume,Ticker,DataSource
0,2025-01-02,138.264694,138.834515,134.585907,135.955453,198247200,NVDA,Yahoo Finance
1,2025-01-03,144.422684,144.852536,139.684231,139.964138,229322500,NVDA,Yahoo Finance
2,2025-01-06,149.381042,152.110159,147.771585,148.541321,265377400,NVDA,Yahoo Finance
3,2025-01-07,140.094086,153.079835,139.964123,152.979862,351782200,NVDA,Yahoo Finance
4,2025-01-08,140.064102,143.902841,137.514934,142.533294,227349900,NVDA,Yahoo Finance

In [14]:
# Download Amazon Market Data

# Download Amazon historical market data
amazon_data = yf.download(
    "AMZN",
    start="2025-01-01",
    end="2026-01-01"
)

# Display the first 5 rows
amazon_data.head()

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker            AMZN        AMZN        AMZN        AMZN      AMZN
Date
2025-01-02  220.220001  225.149994  218.190002  222.029999  33956600
2025-01-03  224.190002  225.360001  221.619995  222.509995  27515600
2025-01-06  227.610001  228.839996  224.839996  226.779999  31849800
2025-01-07  222.110001  228.380005  221.460007  227.899994  28084200
2025-01-08  222.130005  223.520004  220.199997  223.190002  25033300

In [15]:

# Prepare Amazon Data

# Remove the second column level (Ticker)
amazon_data.columns = amazon_data.columns.get_level_values(0)

# Convert the Date index into a normal column
amazon_data = amazon_data.reset_index()

# Remove the remaining column index name
amazon_data.columns.name = None

# Add business metadata
amazon_data["Ticker"] = "AMZN"
amazon_data["DataSource"] = "Yahoo Finance"

# Display the first 5 rows
amazon_data.head()

,Date,Close,High,Low,Open,Volume,Ticker,DataSource
0,2025-01-02,220.220001,225.149994,218.190002,222.029999,33956600,AMZN,Yahoo Finance
1,2025-01-03,224.190002,225.360001,221.619995,222.509995,27515600,AMZN,Yahoo Finance
2,2025-01-06,227.610001,228.839996,224.839996,226.779999,31849800,AMZN,Yahoo Finance
3,2025-01-07,222.110001,228.380005,221.460007,227.899994,28084200,AMZN,Yahoo Finance
4,2025-01-08,222.130005,223.520004,220.199997,223.190002,25033300,AMZN,Yahoo Finance

In [16]:

# Automate Market Data Collection


# List of stock tickers we want to collect
tickers = ["AAPL", "MSFT", "NVDA", "AMZN", "TSLA", "GOOGL"]

# Empty list where we will store each cleaned dataset
all_stock_data = []

# Repeat the same process for every ticker
for ticker in tickers:

    # Download historical market data
    stock_data = yf.download(
        ticker,
        start="2025-01-01",
        end="2026-01-01",
        progress=False
    )

    # Remove the second column level created by Yahoo Finance
    stock_data.columns = stock_data.columns.get_level_values(0)

    # Convert Date from index into a normal column
    stock_data = stock_data.reset_index()

    # Remove the remaining column index name
    stock_data.columns.name = None

    # Add business metadata
    stock_data["Ticker"] = ticker
    stock_data["DataSource"] = "Yahoo Finance"

    # Store the cleaned dataset in the list
    all_stock_data.append(stock_data)

print("Data collection completed.")

Data collection completed.

In [17]:
len(all_stock_data)

6

In [18]:
# Inspect a Dataset from the Collection



# Display the first 5 rows of the Tesla dataset
all_stock_data[4].head()

,Date,Close,High,Low,Open,Volume,Ticker,DataSource
0,2025-01-02,379.279999,392.730011,373.040009,390.100006,109710700,TSLA,Yahoo Finance
1,2025-01-03,410.440002,411.880005,379.450012,381.480011,95423300,TSLA,Yahoo Finance
2,2025-01-06,411.049988,426.429993,401.700012,423.200012,85516500,TSLA,Yahoo Finance
3,2025-01-07,394.359985,414.329987,390.000000,405.829987,75699500,TSLA,Yahoo Finance
4,2025-01-08,394.940002,402.500000,387.399994,392.950012,73038800,TSLA,Yahoo Finance

In [19]:
# Combine All Stock Datasets


# Combine all DataFrames stored in the list
stock_market_data = pd.concat(
    all_stock_data,
    ignore_index=True
)

# Display the first 10 rows
stock_market_data.head(10)

,Date,Close,High,Low,Open,Volume,Ticker,DataSource
0,2025-01-02,242.301910,247.518580,240.284799,247.349646,55740700,AAPL,Yahoo Finance
1,2025-01-03,241.815018,242.629804,240.354349,241.815018,40244100,AAPL,Yahoo Finance
2,2025-01-06,243.444626,245.759836,241.656050,242.759004,45045600,AAPL,Yahoo Finance
3,2025-01-07,240.672318,243.991110,239.817777,241.437418,40856000,AAPL,Yahoo Finance
4,2025-01-08,241.159225,242.162823,238.526055,240.384178,37628900,AAPL,Yahoo Finance
5,2025-01-10,235.346375,238.635359,231.520810,238.486302,61710900,AAPL,Yahoo Finance
6,2025-01-13,232.911926,233.180216,228.261644,232.047454,49630700,AAPL,Yahoo Finance
7,2025-01-14,231.799011,234.620978,230.994156,233.259680,39435300,AAPL,Yahoo Finance
8,2025-01-15,236.359879,237.442970,232.941715,233.150388,39832000,AAPL,Yahoo Finance
9,2025-01-16,226.810898,236.499000,226.582362,235.843202,71759100,AAPL,Yahoo Finance

In [20]:
# Check the number of rows and columns
stock_market_data.shape

(1500, 8)

In [21]:
#Validate the Combined Stock Market Dataset

# Count the number of rows for each ticker
stock_market_data.groupby("Ticker").size()

Ticker
AAPL     250
AMZN     250
GOOGL    250
MSFT     250
NVDA     250
TSLA     250
dtype: int64

In [22]:
# Final Data Quality Check for Stock Market Data


# Check missing values
print("Missing values:")
print(stock_market_data.isnull().sum())

# Check duplicate rows
print("\nDuplicate rows:")
print(stock_market_data.duplicated().sum())

Missing values:
Date          0
Close         0
High          0
Low           0
Open          0
Volume        0
Ticker        0
DataSource    0
dtype: int64

Duplicate rows:
0

In [23]:
# ==========================================================
#  Add Asset Type
#
# Business Purpose:
# Every financial instrument belongs to an asset class such as
# Stock, Index, Forex, Commodity, or Cryptocurrency.
#
# Adding the AssetType column allows us to classify the data,
# making future SQL queries, dashboards, and business analysis
# much easier.
# ==========================================================

# Add AssetType to all stock records
stock_market_data["AssetType"] = "Stock"

# Display the first 5 rows
stock_market_data.head()

,Date,Close,High,Low,Open,Volume,Ticker,DataSource,AssetType
0,2025-01-02,242.301910,247.518580,240.284799,247.349646,55740700,AAPL,Yahoo Finance,Stock
1,2025-01-03,241.815018,242.629804,240.354349,241.815018,40244100,AAPL,Yahoo Finance,Stock
2,2025-01-06,243.444626,245.759836,241.656050,242.759004,45045600,AAPL,Yahoo Finance,Stock
3,2025-01-07,240.672318,243.991110,239.817777,241.437418,40856000,AAPL,Yahoo Finance,Stock
4,2025-01-08,241.159225,242.162823,238.526055,240.384178,37628900,AAPL,Yahoo Finance,Stock

In [24]:
# Download Market Indices
# List of market indices
indices = ["^GSPC", "^NDX", "^DJI"]

# Empty list to store index datasets
all_index_data = []

# Download and prepare each index
for index in indices:

    index_data = yf.download(
        index,
        start="2025-01-01",
        end="2026-01-01",
        progress=False
    )

    # Standardize the dataset
    index_data.columns = index_data.columns.get_level_values(0)
    index_data = index_data.reset_index()
    index_data.columns.name = None

    # Add business metadata
    index_data["Ticker"] = index
    index_data["AssetType"] = "Index"
    index_data["DataSource"] = "Yahoo Finance"

    # Store the dataset
    all_index_data.append(index_data)

print("Market indices downloaded successfully.")

Market indices downloaded successfully.

In [25]:
len(all_index_data)

3

In [26]:
# Inspect the S&P 500 Dataset


# Display the first 5 rows of the S&P 500 dataset
all_index_data[0].head()

,Date,Close,High,Low,Open,Volume,Ticker,AssetType,DataSource
0,2025-01-02,5868.549805,5935.089844,5829.529785,5903.259766,3621680000,^GSPC,Index,Yahoo Finance
1,2025-01-03,5942.470215,5949.339844,5888.660156,5891.069824,3667340000,^GSPC,Index,Yahoo Finance
2,2025-01-06,5975.379883,6021.040039,5960.009766,5982.810059,4940120000,^GSPC,Index,Yahoo Finance
3,2025-01-07,5909.029785,6000.680176,5890.680176,5993.259766,4517330000,^GSPC,Index,Yahoo Finance
4,2025-01-08,5918.250000,5927.890137,5874.779785,5910.660156,4441740000,^GSPC,Index,Yahoo Finance

In [27]:
#Combine All Market Indices


# Combine all index datasets
index_market_data = pd.concat(
    all_index_data,
    ignore_index=True
)

# Display the first 10 rows
index_market_data.head(10)

,Date,Close,High,Low,Open,Volume,Ticker,AssetType,DataSource
0,2025-01-02,5868.549805,5935.089844,5829.529785,5903.259766,3621680000,^GSPC,Index,Yahoo Finance
1,2025-01-03,5942.470215,5949.339844,5888.660156,5891.069824,3667340000,^GSPC,Index,Yahoo Finance
2,2025-01-06,5975.379883,6021.040039,5960.009766,5982.810059,4940120000,^GSPC,Index,Yahoo Finance
3,2025-01-07,5909.029785,6000.680176,5890.680176,5993.259766,4517330000,^GSPC,Index,Yahoo Finance
4,2025-01-08,5918.250000,5927.890137,5874.779785,5910.660156,4441740000,^GSPC,Index,Yahoo Finance
5,2025-01-10,5827.040039,5890.350098,5807.779785,5890.350098,4751930000,^GSPC,Index,Yahoo Finance
6,2025-01-13,5836.220215,5838.609863,5773.310059,5782.020020,4421200000,^GSPC,Index,Yahoo Finance
7,2025-01-14,5842.910156,5871.919922,5805.419922,5859.270020,4142280000,^GSPC,Index,Yahoo Finance
8,2025-01-15,5949.910156,5960.609863,5905.209961,5905.209961,4544570000,^GSPC,Index,Yahoo Finance
9,2025-01-16,5937.339844,5964.689941,5930.720215,5963.609863,4285810000,^GSPC,Index,Yahoo Finance

In [28]:
index_market_data.shape

(750, 9)

In [29]:
# Download Forex Market Data


# List of currency pairs
currencies = [
    "EURUSD=X",
    "GBPUSD=X",
    "USDJPY=X"
]

# Empty list to store Forex datasets
all_forex_data = []

# Download and prepare each currency pair
for currency in currencies:

    forex_data = yf.download(
        currency,
        start="2025-01-01",
        end="2026-01-01",
        progress=False
    )

    # Standardize the dataset
    forex_data.columns = forex_data.columns.get_level_values(0)
    forex_data = forex_data.reset_index()
    forex_data.columns.name = None

    # Add business metadata
    forex_data["Ticker"] = currency
    forex_data["AssetType"] = "Forex"
    forex_data["DataSource"] = "Yahoo Finance"

    # Store the dataset
    all_forex_data.append(forex_data)

print("Forex market data downloaded successfully.")

Forex market data downloaded successfully.

In [30]:
len(all_forex_data)

3

In [31]:
# Step 25: Inspect the EUR/USD Dataset

# Display the first 5 rows of the EUR/USD dataset
all_forex_data[0].head()

,Date,Close,High,Low,Open,Volume,Ticker,AssetType,DataSource
0,2025-01-02,1.035186,1.037560,1.023185,1.035186,0,EURUSD=X,Forex,Yahoo Finance
1,2025-01-03,1.026821,1.030535,1.026546,1.026821,0,EURUSD=X,Forex,Yahoo Finance
2,2025-01-06,1.030535,1.043504,1.029633,1.030535,0,EURUSD=X,Forex,Yahoo Finance
3,2025-01-07,1.038637,1.043623,1.035947,1.038637,0,EURUSD=X,Forex,Yahoo Finance
4,2025-01-08,1.034554,1.035840,1.027675,1.034554,0,EURUSD=X,Forex,Yahoo Finance

In [32]:
#Combine All Forex Datasets

# Combine all Forex datasets
forex_market_data = pd.concat(
    all_forex_data,
    ignore_index=True
)

# Display the first 10 rows
forex_market_data.head(10)

,Date,Close,High,Low,Open,Volume,Ticker,AssetType,DataSource
0,2025-01-02,1.035186,1.037560,1.023185,1.035186,0,EURUSD=X,Forex,Yahoo Finance
1,2025-01-03,1.026821,1.030535,1.026546,1.026821,0,EURUSD=X,Forex,Yahoo Finance
2,2025-01-06,1.030535,1.043504,1.029633,1.030535,0,EURUSD=X,Forex,Yahoo Finance
3,2025-01-07,1.038637,1.043623,1.035947,1.038637,0,EURUSD=X,Forex,Yahoo Finance
4,2025-01-08,1.034554,1.035840,1.027675,1.034554,0,EURUSD=X,Forex,Yahoo Finance
5,2025-01-09,1.031470,1.032311,1.028616,1.031470,0,EURUSD=X,Forex,Yahoo Finance
6,2025-01-10,1.029760,1.031194,1.022119,1.029760,0,EURUSD=X,Forex,Yahoo Finance
7,2025-01-13,1.024443,1.025021,1.018382,1.024443,0,EURUSD=X,Forex,Yahoo Finance
8,2025-01-14,1.026525,1.030397,1.023971,1.026525,0,EURUSD=X,Forex,Yahoo Finance
9,2025-01-15,1.030684,1.035025,1.027063,1.030684,0,EURUSD=X,Forex,Yahoo Finance

In [33]:
# Check the number of rows and columns
forex_market_data.shape

(771, 9)

In [34]:
# Validate Forex Records by Currency Pair


forex_market_data.groupby("Ticker").size()

Ticker
EURUSD=X    257
GBPUSD=X    257
USDJPY=X    257
dtype: int64

In [35]:
# Final Data Quality Check for Forex


# Check missing values
print("Missing values:")
print(forex_market_data.isnull().sum())

# Check duplicate rows
print("\nDuplicate rows:")
print(forex_market_data.duplicated().sum())

Missing values:
Date          0
Close         0
High          0
Low           0
Open          0
Volume        0
Ticker        0
AssetType     0
DataSource    0
dtype: int64

Duplicate rows:
0

In [36]:
#  Download Commodity Market Data


commodities = [
    "GC=F",   # Gold Futures
    "SI=F",   # Silver Futures
    "CL=F"    # Crude Oil Futures
]

# Empty list to store commodity datasets
all_commodity_data = []

# Download and prepare each commodity
for commodity in commodities:

    commodity_data = yf.download(
        commodity,
        start="2025-01-01",
        end="2026-01-01",
        progress=False
    )

    # Standardize the dataset
    commodity_data.columns = commodity_data.columns.get_level_values(0)
    commodity_data = commodity_data.reset_index()
    commodity_data.columns.name = None

    # Add business metadata
    commodity_data["Ticker"] = commodity
    commodity_data["AssetType"] = "Commodity"
    commodity_data["DataSource"] = "Yahoo Finance"

    # Store the dataset
    all_commodity_data.append(commodity_data)

print("Commodity market data downloaded successfully.")

Commodity market data downloaded successfully.

In [37]:
len(all_commodity_data)

3

In [38]:

#  Inspect the Gold Dataset


# Display the first 5 rows of the Gold dataset
all_commodity_data[0].head()

,Date,Close,High,Low,Open,Volume,Ticker,AssetType,DataSource
0,2025-01-02,2658.899902,2663.100098,2633.000000,2633.000000,1728,GC=F,Commodity,Yahoo Finance
1,2025-01-03,2645.000000,2658.699951,2641.800049,2658.699951,591,GC=F,Commodity,Yahoo Finance
2,2025-01-06,2638.399902,2647.000000,2617.300049,2645.500000,960,GC=F,Commodity,Yahoo Finance
3,2025-01-07,2656.699951,2657.500000,2653.000000,2653.399902,643,GC=F,Commodity,Yahoo Finance
4,2025-01-08,2664.500000,2676.899902,2653.500000,2655.500000,999,GC=F,Commodity,Yahoo Finance

In [39]:

# Combine All Commodity Datasets



# Combine all commodity datasets
commodity_market_data = pd.concat(
    all_commodity_data,
    ignore_index=True
)

# Display the first 10 rows
commodity_market_data.head(10)

,Date,Close,High,Low,Open,Volume,Ticker,AssetType,DataSource
0,2025-01-02,2658.899902,2663.100098,2633.000000,2633.000000,1728,GC=F,Commodity,Yahoo Finance
1,2025-01-03,2645.000000,2658.699951,2641.800049,2658.699951,591,GC=F,Commodity,Yahoo Finance
2,2025-01-06,2638.399902,2647.000000,2617.300049,2645.500000,960,GC=F,Commodity,Yahoo Finance
3,2025-01-07,2656.699951,2657.500000,2653.000000,2653.399902,643,GC=F,Commodity,Yahoo Finance
4,2025-01-08,2664.500000,2676.899902,2653.500000,2655.500000,999,GC=F,Commodity,Yahoo Finance
5,2025-01-09,2683.800049,2686.300049,2667.899902,2669.699951,1139,GC=F,Commodity,Yahoo Finance
6,2025-01-10,2708.500000,2720.100098,2683.699951,2686.100098,403,GC=F,Commodity,Yahoo Finance
7,2025-01-13,2673.500000,2711.199951,2673.500000,2711.100098,765,GC=F,Commodity,Yahoo Finance
8,2025-01-14,2677.500000,2688.300049,2670.800049,2673.600098,794,GC=F,Commodity,Yahoo Finance
9,2025-01-15,2712.500000,2712.500000,2690.800049,2690.800049,930,GC=F,Commodity,Yahoo Finance

In [40]:

# Validate Commodity Records


# Count records for each commodity
commodity_market_data.groupby("Ticker").size()

Ticker
CL=F    252
GC=F    252
SI=F    252
dtype: int64

In [41]:
# Final Data Quality Check for Commodities

# Check missing values
print("Missing values:")
print(commodity_market_data.isnull().sum())

# Check duplicate rows
print("\nDuplicate rows:")
print(commodity_market_data.duplicated().sum())

Missing values:
Date          0
Close         0
High          0
Low           0
Open          0
Volume        0
Ticker        0
AssetType     0
DataSource    0
dtype: int64

Duplicate rows:
0

In [42]:
# Step 31: Combine All Commodity Datasets


# Combine all commodity datasets
commodity_market_data = pd.concat(
    all_commodity_data,
    ignore_index=True
)

# Display the first 10 rows
commodity_market_data.head(10)

,Date,Close,High,Low,Open,Volume,Ticker,AssetType,DataSource
0,2025-01-02,2658.899902,2663.100098,2633.000000,2633.000000,1728,GC=F,Commodity,Yahoo Finance
1,2025-01-03,2645.000000,2658.699951,2641.800049,2658.699951,591,GC=F,Commodity,Yahoo Finance
2,2025-01-06,2638.399902,2647.000000,2617.300049,2645.500000,960,GC=F,Commodity,Yahoo Finance
3,2025-01-07,2656.699951,2657.500000,2653.000000,2653.399902,643,GC=F,Commodity,Yahoo Finance
4,2025-01-08,2664.500000,2676.899902,2653.500000,2655.500000,999,GC=F,Commodity,Yahoo Finance
5,2025-01-09,2683.800049,2686.300049,2667.899902,2669.699951,1139,GC=F,Commodity,Yahoo Finance
6,2025-01-10,2708.500000,2720.100098,2683.699951,2686.100098,403,GC=F,Commodity,Yahoo Finance
7,2025-01-13,2673.500000,2711.199951,2673.500000,2711.100098,765,GC=F,Commodity,Yahoo Finance
8,2025-01-14,2677.500000,2688.300049,2670.800049,2673.600098,794,GC=F,Commodity,Yahoo Finance
9,2025-01-15,2712.500000,2712.500000,2690.800049,2690.800049,930,GC=F,Commodity,Yahoo Finance

In [43]:
# Step 32: Validate Commodity Records


commodity_market_data.groupby("Ticker").size()

Ticker
CL=F    252
GC=F    252
SI=F    252
dtype: int64

In [44]:

# Final Data Quality Check


print("Missing values:")
print(commodity_market_data.isnull().sum())

print("\nDuplicate rows:")
print(commodity_market_data.duplicated().sum())

Missing values:
Date          0
Close         0
High          0
Low           0
Open          0
Volume        0
Ticker        0
AssetType     0
DataSource    0
dtype: int64

Duplicate rows:
0

In [45]:
# Download Cryptocurrency Market Data



# List of cryptocurrencies
cryptocurrencies = [
    "BTC-USD",  # Bitcoin
    "ETH-USD",  # Ethereum
    "SOL-USD"   # Solana
]

# Empty list to store cryptocurrency datasets
all_crypto_data = []

# Download and prepare each cryptocurrency
for crypto in cryptocurrencies:

    crypto_data = yf.download(
        crypto,
        start="2025-01-01",
        end="2026-01-01",
        progress=False
    )

    # Standardize the dataset
    crypto_data.columns = crypto_data.columns.get_level_values(0)
    crypto_data = crypto_data.reset_index()
    crypto_data.columns.name = None

    # Add business metadata
    crypto_data["Ticker"] = crypto
    crypto_data["AssetType"] = "Cryptocurrency"
    crypto_data["DataSource"] = "Yahoo Finance"

    # Store the dataset
    all_crypto_data.append(crypto_data)

print("Cryptocurrency market data downloaded successfully.")

Cryptocurrency market data downloaded successfully.

In [46]:
len(all_crypto_data)

3

In [47]:

# Inspect the Bitcoin Dataset


# Display the first 5 rows of Bitcoin data
all_crypto_data[0].head()

,Date,Close,High,Low,Open,Volume,Ticker,AssetType,DataSource
0,2025-01-01,94419.757812,94929.867188,92788.125000,93425.101562,24519888919,BTC-USD,Cryptocurrency,Yahoo Finance
1,2025-01-02,96886.875000,97739.820312,94201.570312,94416.289062,46009564411,BTC-USD,Cryptocurrency,Yahoo Finance
2,2025-01-03,98107.429688,98956.914062,96034.617188,96881.726562,35611391163,BTC-USD,Cryptocurrency,Yahoo Finance
3,2025-01-04,98236.226562,98734.429688,97562.976562,98106.992188,22342608078,BTC-USD,Cryptocurrency,Yahoo Finance
4,2025-01-05,98314.960938,98813.304688,97291.765625,98233.906250,20525254825,BTC-USD,Cryptocurrency,Yahoo Finance

In [48]:
# Step 36: Combine All Cryptocurrency Datasets


# Combine all cryptocurrency datasets
crypto_market_data = pd.concat(
    all_crypto_data,
    ignore_index=True
)

# Display the first 10 rows
crypto_market_data.head(10)

,Date,Close,High,Low,Open,Volume,Ticker,AssetType,DataSource
0,2025-01-01,94419.757812,94929.867188,92788.125000,93425.101562,24519888919,BTC-USD,Cryptocurrency,Yahoo Finance
1,2025-01-02,96886.875000,97739.820312,94201.570312,94416.289062,46009564411,BTC-USD,Cryptocurrency,Yahoo Finance
2,2025-01-03,98107.429688,98956.914062,96034.617188,96881.726562,35611391163,BTC-USD,Cryptocurrency,Yahoo Finance
3,2025-01-04,98236.226562,98734.429688,97562.976562,98106.992188,22342608078,BTC-USD,Cryptocurrency,Yahoo Finance
4,2025-01-05,98314.960938,98813.304688,97291.765625,98233.906250,20525254825,BTC-USD,Cryptocurrency,Yahoo Finance
5,2025-01-06,102078.085938,102482.875000,97926.148438,98314.953125,51823432705,BTC-USD,Cryptocurrency,Yahoo Finance
6,2025-01-07,96922.703125,102712.484375,96132.875000,102248.851562,58685738547,BTC-USD,Cryptocurrency,Yahoo Finance
7,2025-01-08,95043.523438,97258.320312,92525.843750,96924.164062,63875859171,BTC-USD,Cryptocurrency,Yahoo Finance
8,2025-01-09,92484.039062,95349.718750,91220.843750,95043.484375,62777261693,BTC-USD,Cryptocurrency,Yahoo Finance
9,2025-01-10,94701.453125,95770.609375,92250.093750,92494.492188,62058693684,BTC-USD,Cryptocurrency,Yahoo Finance

In [49]:

# Validate Cryptocurrency Records


crypto_market_data.groupby("Ticker").size()

Ticker
BTC-USD    365
ETH-USD    365
SOL-USD    365
dtype: int64

In [50]:

# Final Data Quality Check for Cryptocurrency


print("Missing values:")
print(crypto_market_data.isnull().sum())

print("\nDuplicate rows:")
print(crypto_market_data.duplicated().sum())

Missing values:
Date          0
Close         0
High          0
Low           0
Open          0
Volume        0
Ticker        0
AssetType     0
DataSource    0
dtype: int64

Duplicate rows:
0

In [51]:
# ==========================================================
#  Create the MarketPrices Fact Table
#
# Business Purpose:
# Combine every validated asset class into one centralized
# MarketPrices table.
#
# This table becomes the primary source for SQL analysis,
# reporting, dashboards, and business intelligence.
# ==========================================================

# Combine all asset classes
market_prices = pd.concat(
    [
        stock_market_data,
        index_market_data,
        forex_market_data,
        commodity_market_data,
        crypto_market_data
    ],
    ignore_index=True
)

# Display first 10 rows
market_prices.head(10)

,Date,Close,High,Low,Open,Volume,Ticker,DataSource,AssetType
0,2025-01-02,242.301910,247.518580,240.284799,247.349646,55740700,AAPL,Yahoo Finance,Stock
1,2025-01-03,241.815018,242.629804,240.354349,241.815018,40244100,AAPL,Yahoo Finance,Stock
2,2025-01-06,243.444626,245.759836,241.656050,242.759004,45045600,AAPL,Yahoo Finance,Stock
3,2025-01-07,240.672318,243.991110,239.817777,241.437418,40856000,AAPL,Yahoo Finance,Stock
4,2025-01-08,241.159225,242.162823,238.526055,240.384178,37628900,AAPL,Yahoo Finance,Stock
5,2025-01-10,235.346375,238.635359,231.520810,238.486302,61710900,AAPL,Yahoo Finance,Stock
6,2025-01-13,232.911926,233.180216,228.261644,232.047454,49630700,AAPL,Yahoo Finance,Stock
7,2025-01-14,231.799011,234.620978,230.994156,233.259680,39435300,AAPL,Yahoo Finance,Stock
8,2025-01-15,236.359879,237.442970,232.941715,233.150388,39832000,AAPL,Yahoo Finance,Stock
9,2025-01-16,226.810898,236.499000,226.582362,235.843202,71759100,AAPL,Yahoo Finance,Stock

In [52]:
# ==========================================================
# Create the Instruments Dimension Table
#
# Business Purpose:
# Create a reference table containing descriptive information
# about every financial instrument. This table will be linked
# to the MarketPrices fact table through the Ticker column.
# ==========================================================

import pandas as pd

instruments = pd.DataFrame({

    "Ticker": [
        "AAPL",
        "MSFT",
        "NVDA",
        "AMZN",
        "TSLA",
        "GOOGL",
        "^GSPC",
        "^NDX",
        "^DJI",
        "EURUSD=X",
        "GBPUSD=X",
        "USDJPY=X",
        "GC=F",
        "SI=F",
        "CL=F",
        "BTC-USD",
        "ETH-USD",
        "SOL-USD"
    ],

    "InstrumentName": [
        "Apple Inc.",
        "Microsoft Corporation",
        "NVIDIA Corporation",
        "Amazon.com Inc.",
        "Tesla Inc.",
        "Alphabet Inc.",
        "S&P 500",
        "NASDAQ-100",
        "Dow Jones Industrial Average",
        "Euro / US Dollar",
        "British Pound / US Dollar",
        "US Dollar / Japanese Yen",
        "Gold Futures",
        "Silver Futures",
        "Crude Oil Futures",
        "Bitcoin",
        "Ethereum",
        "Solana"
    ],

    "AssetType": [
        "Stock","Stock","Stock","Stock","Stock","Stock",
        "Index","Index","Index",
        "Forex","Forex","Forex",
        "Commodity","Commodity","Commodity",
        "Cryptocurrency","Cryptocurrency","Cryptocurrency"
    ],

    "Sector": [
        "Technology",
        "Technology",
        "Technology",
        "Consumer Discretionary",
        "Consumer Discretionary",
        "Technology",
        "Market Index",
        "Market Index",
        "Market Index",
        "Currency",
        "Currency",
        "Currency",
        "Precious Metals",
        "Precious Metals",
        "Energy",
        "Digital Assets",
        "Digital Assets",
        "Digital Assets"
    ],

    "Currency": [
        "USD","USD","USD","USD","USD","USD",
        "USD","USD","USD",
        "EUR/USD",
        "GBP/USD",
        "USD/JPY",
        "USD",
        "USD",
        "USD",
        "USD",
        "USD",
        "USD"
    ],

    "Exchange": [
        "NASDAQ",
        "NASDAQ",
        "NASDAQ",
        "NASDAQ",
        "NASDAQ",
        "NASDAQ",
        "S&P",
        "NASDAQ",
        "NYSE",
        "Forex Market",
        "Forex Market",
        "Forex Market",
        "COMEX",
        "COMEX",
        "NYMEX",
        "Crypto Market",
        "Crypto Market",
        "Crypto Market"
    ]
})

# Display the table
instruments

,Ticker,InstrumentName,AssetType,Sector,Currency,Exchange
0,AAPL,Apple Inc.,Stock,Technology,USD,NASDAQ
1,MSFT,Microsoft Corporation,Stock,Technology,USD,NASDAQ
2,NVDA,NVIDIA Corporation,Stock,Technology,USD,NASDAQ
3,AMZN,Amazon.com Inc.,Stock,Consumer Discretionary,USD,NASDAQ
4,TSLA,Tesla Inc.,Stock,Consumer Discretionary,USD,NASDAQ
5,GOOGL,Alphabet Inc.,Stock,Technology,USD,NASDAQ
6,^GSPC,S&P 500,Index,Market Index,USD,S&P
7,^NDX,NASDAQ-100,Index,Market Index,USD,NASDAQ
8,^DJI,Dow Jones Industrial Average,Index,Market Index,USD,NYSE
9,EURUSD=X,Euro / US Dollar,Forex,Currency,EUR/USD,Forex Market
10,GBPUSD=X,British Pound / US Dollar,Forex,Currency,GBP/USD,Forex Market
11,USDJPY=X,US Dollar / Japanese Yen,Forex,Currency,USD/JPY,Forex Market
12,GC=F,Gold Futures,Commodity,Precious Metals,USD,COMEX
13,SI=F,Silver Futures,Commodity,Precious Metals,USD,COMEX
14,CL=F,Crude Oil Futures,Commodity,Energy,USD,NYMEX
15,BTC-USD,Bitcoin,Cryptocurrency,Digital Assets,USD,Crypto Market
16,ETH-USD,Ethereum,Cryptocurrency,Digital Assets,USD,Crypto Market
17,SOL-USD,Solana,Cryptocurrency,Digital Assets,USD,Crypto Market

In [53]:

# Validate the Instruments Dimension Table


# Check the number of rows and columns
print("Table shape:", instruments.shape)

# Check for missing values
print("\nMissing values:")
print(instruments.isnull().sum())

# Check for duplicate tickers
print("\nDuplicate tickers:")
print(instruments["Ticker"].duplicated().sum())

Table shape: (18, 6)

Missing values:
Ticker            0
InstrumentName    0
AssetType         0
Sector            0
Currency          0
Exchange          0
dtype: int64

Duplicate tickers:
0

In [54]:
# ==========================================================
# Validate the Fact–Dimension Relationship


# Get unique tickers from both tables
fact_tickers = set(market_prices["Ticker"].unique())
dimension_tickers = set(instruments["Ticker"].unique())

# Find tickers that exist in MarketPrices but not in Instruments
missing_instruments = fact_tickers - dimension_tickers

print("Unique tickers in MarketPrices:", len(fact_tickers))
print("Unique tickers in Instruments:", len(dimension_tickers))
print("Missing instrument records:", missing_instruments)

Unique tickers in MarketPrices: 18
Unique tickers in Instruments: 18
Missing instrument records: set()

In [56]:
# ==========================================================
# Step 4: Connect Python to SQL Server
#
# Business Purpose:
# Establish a connection between Python and SQL Server.
# This allows Python to load validated market data directly
# into the database without manual CSV imports.
# ==========================================================

from sqlalchemy import create_engine
from urllib.parse import quote_plus

# SQL Server connection settings
server = "localhost"
database = "MarketDataWarehouse"

# ODBC Driver
driver = quote_plus("ODBC Driver 17 for SQL Server")

# Create SQLAlchemy engine
engine = create_engine(
    f"mssql+pyodbc://@{server}/{database}"
    f"?driver={driver}"
    "&trusted_connection=yes"
)

print("Connection created successfully!")

Connection created successfully!

In [57]:

# Step 5: Test the SQL Server Connection


# Simple SQL query
query = "SELECT DB_NAME() AS CurrentDatabase;"

# Execute the query
result = pd.read_sql(query, engine)

# Display the result
result

C:\Users\xayal\anaconda3\Lib\site-packages\pandas\io\sql.py:1649: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

       CurrentDatabase
0  MarketDataWarehouse

In [58]:

# Load the Instruments Dimension Table

instruments.to_sql(
    name="Instruments",
    con=engine,
    if_exists="append",
    index=False
)

print("Instruments table loaded successfully.")

Instruments table loaded successfully.

In [59]:

# Validate the Instruments Table in SQL Server


query = """
SELECT 
    COUNT(*) AS TotalInstruments
FROM Instruments;
"""

instrument_count = pd.read_sql(query, engine)

instrument_count

   TotalInstruments
0                18

In [60]:

# Preview Instruments Data from SQL Server


query = """
SELECT TOP 10 *
FROM Instruments
ORDER BY Ticker;
"""

instrument_preview = pd.read_sql(query, engine)

instrument_preview

,Ticker,InstrumentName,AssetType,Sector,Currency,Exchange
0,^DJI,Dow Jones Industrial Average,Index,Market Index,USD,NYSE
1,^GSPC,S&P 500,Index,Market Index,USD,S&P
2,^NDX,NASDAQ-100,Index,Market Index,USD,NASDAQ
3,AAPL,Apple Inc.,Stock,Technology,USD,NASDAQ
4,AMZN,Amazon.com Inc.,Stock,Consumer Discretionary,USD,NASDAQ
5,BTC-USD,Bitcoin,Cryptocurrency,Digital Assets,USD,Crypto Market
6,CL=F,Crude Oil Futures,Commodity,Energy,USD,NYMEX
7,ETH-USD,Ethereum,Cryptocurrency,Digital Assets,USD,Crypto Market
8,EURUSD=X,Euro / US Dollar,Forex,Currency,EUR/USD,Forex Market
9,GBPUSD=X,British Pound / US Dollar,Forex,Currency,GBP/USD,Forex Market

In [61]:

# Prepare the MarketPrices DataFrame for SQL Server


market_prices_sql = market_prices.rename(columns={
    "Open": "OpenPrice",
    "High": "HighPrice",
    "Low": "LowPrice",
    "Close": "ClosePrice"
})

# Display the first 5 rows
market_prices_sql.head()

,Date,ClosePrice,HighPrice,LowPrice,OpenPrice,Volume,Ticker,DataSource,AssetType
0,2025-01-02,242.301910,247.518580,240.284799,247.349646,55740700,AAPL,Yahoo Finance,Stock
1,2025-01-03,241.815018,242.629804,240.354349,241.815018,40244100,AAPL,Yahoo Finance,Stock
2,2025-01-06,243.444626,245.759836,241.656050,242.759004,45045600,AAPL,Yahoo Finance,Stock
3,2025-01-07,240.672318,243.991110,239.817777,241.437418,40856000,AAPL,Yahoo Finance,Stock
4,2025-01-08,241.159225,242.162823,238.526055,240.384178,37628900,AAPL,Yahoo Finance,Stock

In [62]:

# Load the MarketPrices Fact Table



market_prices_sql.to_sql(
    name="MarketPrices",
    con=engine,
    if_exists="append",
    index=False,
    chunksize=500
)

print("MarketPrices table loaded successfully.")

MarketPrices table loaded successfully.

In [63]:
# Verify the MarketPrices Fact Table


query = """
SELECT COUNT(*) AS TotalMarketPrices
FROM MarketPrices;
"""

market_count = pd.read_sql(query, engine)

market_count

   TotalMarketPrices
0               4872